### ISSUE TITLE
Similarity examples not working with Wikipedia model

### ISSUE THREAD

**Issue by sradu** [3Top/word2vec-api#11]
Running word2vec-api like:
`python word2vec-api.py --model glove.6B.300d-with-header.txt --host 127.0.0.1 --port 8080`

$ curl "http://127.0.0.1:8080/word2vec/n_similarity?ws1=Sushi&ws1=Shop&ws2=Japanese&ws2=Restaurant"
NaN
GET /word2vec/most_similar?positive=indian&positive=food HTTP/1.1" 200 -
/ts/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/ts/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

$ curl "http://127.0.0.1:8080/word2vec/similarity?w1=Sushi&w2=Japanese"
{"message": "Internal Server Error"}

Any suggestions?

**Comment by lechatpito** [comment]
You need to make sure that words you query are in the vocabulary. Each model potentially has a different vocabulary. Also beware case-sensitivity. There should probably be better error handling to return a message saying that the terms queried are not in the vocabulary.
