### ISSUE TITLE
Using word2vec-api with GloVe pre-trained models

### ISSUE THREAD

**Issue by ikatanic** [3Top/word2vec-api#12]
Hi,

how do you use this with GloVe models listed in readme? For example Wikipedia+Gigaword 5?
It looks like it should be preprocessed before giving it as a model to word2vec-api.

I see there is `clean-word2vec-text-format.py` script that looks like it might be useful, but it seems that it expects different format (number of words and dimension, on the first line of txt file). I tried adding that line but output file looks almost the same and doesn't work with word2vec-api.

Thanks

**Comment by ikatanic** [comment]
Nevermind, figured it out.
If anyone is wondering, it suffices to add line mentioned in the question to the beginning of the txt file, and then just give it directly to word2vec-api.

**Comment by mohdgadi** [comment]
Could you please elaborate how to use a glove txt model

**Comment by eveningkid** [comment]
@mohdgadi I bet that @ikatanic refers to [@lechatpito's message here](https://github.com/3Top/word2vec-api/issues/6#issuecomment-179339511).

Long story short, add a line at the top of the file such as:
```
vocab_size dimension
e.g: 400000 300
```
You'll find the model's corresponding information on the README file.

**Comment by Justicea83** [comment]
https://github.com/3Top/word2vec-api/issues/6#issuecomment-370193754

This works perfectly
