### ISSUE TITLE
gunzip claims the pretrained models aren't in gzip format

### ISSUE THREAD

**Issue by dansbecker** [3Top/word2vec-api#3]
The pretrained models have file extensions (gz) indicating they are gzipped, but they appear to be plaintext (txt).

**Comment by lechatpito** [comment]
Each model provider uses its own format. What model are you having problems with ?

**Comment by dansbecker** [comment]
I've downloaded all of the files with 6B and twitter in the name.  They all end with gz, and they are all plaintext files.

**Comment by dansbecker** [comment]
The issue is literally just that the file extensions are .bin.gz and the files are plaintext files (that can be opened in sublime or vim).

This is consistent across model providers.
