### ISSUE TITLE
ImportError: cannot import name 'Markup' from 'jinja2' when launching the service

### ISSUE THREAD

**Issue by redouane20-1** [3Top/word2vec-api#31]
When I try to launch the service, I get this error:
 
```
Traceback (most recent call last):
  File "word2vec-api.py", line 13, in <module>
    from flask import Flask, request, jsonify
  File "C:\Users\user1\anaconda3\envs\py373\lib\site-packages\flask\__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\user1\anaconda3\envs\py373\lib\site-packages\jinja2\__init__.py)
```

So I wanna know if this API can use flask 2.x.x instead of flask 1.0.2

**Comment by lechatpito** [comment]
Hello, it seems we will need to upgrade dependencies to allow this. Please
feel free to go ahead and submit a PR if you have the possibility to do so.
Otherwise we will tackle it as soon as reasonably possible.

**Comment by redouane20-1** [comment]
Hi! After updating the requirements.txt file by removing the versions of flask, flask REST-full and future, it works fine.

**Comment by m0-n** [comment]
Updating requirements.txt to:

```
Flask==2.2.2
Flask-RESTful==0.3.9
gensim==3.6.0
future==0.18.2

```

And running:

`python3 word2vec-api.py --model yourmodel.bin --binary BINARY --path /word2vec --host 0.0.0.0 --port 5000`

did work for me (spent about 5mins on it, so not sure about any changes this may imply, use with caution).
