### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'the'

### ISSUE THREAD

**Issue by Stamenov** [3Top/word2vec-api#6]
>   File "/Users/user/.virtualenvs/word2vec/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1026, in load_word2vec_format
>     vocab_size, vector_size = map(int, header.split())  # throws for invalid file format
> ValueError: invalid literal for int() with base 10: 'the'

I get the following error when i run `python word2vec-api.py --model glove.6B.50d.txt`

And this happens with every other pre-trained model that is in .txt formal.
I set the binary property to False.
Even tried with different files/pre-trained models with observable length.

I also ran load_word2vec_format from the console on my own, still getting the same error. Should I preprocess the files beforehand? Seems also to be picking the wrong format.

Thanks!

**Comment by lechatpito** [comment]
Each corpus need to start with a line containing the vocab size and the vector size in that order. So in this case you need to add this line "400000 50" as the first line of the model. Let me know if that helped.

**Comment by Stamenov** [comment]
@lechatpito 
Worked like a charm! 
Thanks for the quick response!
Greets.

**Comment by andreamad8** [comment]
Hi, I have got the same problem. If 
```python
word2vec_model_file='../embeddings/myfile.bin'

model = Word2Vec.load_word2vec_format(word2vec_model_file, binary=True,encoding="ISO-8859-1")
```
and I have the following:
    model = Word2Vec.load_word2vec_format(word2vec_model_file, binary=False,encoding="ISO-8859-1")
  File "/home/andrea/anaconda3/lib/python3.5/site-packages/gensim/models/word2vec.py", line 1173, in load_word2vec_format
    vocab_size, vector_size = map(int, header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: '\x80\x02cgensim.models.word2vec'
Any suggestion ?

Thanks in advance 

Andrea

**Comment by lechatpito** [comment]
you need to pass --binary=BINARY as an argument.

**Comment by brajagopalcse** [comment]
Hi, 
I got this same error while importing the Stanford Glove model. 

Line 16: 
modelGlove = gensim.models.KeyedVectors.load_word2vec_format('/home/bpatra/Downloads/glove.twitter.27B/glove.twitter.27B.200d.txt', binary=False, encoding="ISO-8859-1")

Error: 

File "processTweetsGlove.py", line 16, in <module>
    modelGlove = gensim.models.KeyedVectors.load_word2vec_format('/home/user/Downloads/glove.twitter.27B/glove.twitter.27B.200d.txt', binary=False, encoding="ISO-8859-1")
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/keyedvectors.py", line 194, in load_word2vec_format
    vocab_size, vector_size = map(int, header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: '<user>'

Even I tried with encoding = 'utf-8' and I got the same error.

Thanks in advance, 
Braja

**Comment by andreamad8** [comment]
Hi,

Glove does not follows Word2Vec format, which include a line of header with information about the number of word and other info.

You can try this: https://github.com/jroakes/glove-to-word2vec to convert it and use it with gensim

Hope this will help you

Cheers 

Andrea

**Comment by brajagopalcse** [comment]
Hi Andrea, 
Thanks a lot. It worked. 
Braja

**Comment by lechatpito** [comment]
GloVe models miss the 1st line containing `vocabulary_size dimension_size`. You can either open the  file and put this info yourself, or use the converter @andreamad8 has mentioned.

**Comment by brajagopalcse** [comment]
Thanks @lechatpito. I did in both the ways. :)

**Comment by micimize** [comment]
gensim has a built in script [gensim.scripts.glove2word2vec](https://radimrehurek.com/gensim/scripts/glove2word2vec.html):
`python -m  gensim.scripts.glove2word2vec -i glove.6B.300d.txt -o glove.6B.300d.word2vec.txt`

**Comment by lechatpito** [comment]
Yep, thanks for the tip Michael.

**Comment by sbcool01** [comment]
Hi @andreamad8 @lechatpito 
I am loading .bin file. 
Can you please elaborate how to use --binary=BINARY. Since I am a newbie I am not able to use it. 
Thanks in advance,
Swayam

**Comment by Pranjalya** [comment]
@sbcool01 Since you are loading a binary pre-trained model, you just have to pass binary flag as true, as in here : 
modelGlove = gensim.models.KeyedVectors.load_word2vec_format(/path/to/embedding/file.bin', **binary=True**, encoding="utf-8")

**Comment by rajatjain2310** [comment]
> Each corpus need to start with a line containing the vocab size and the vector size in that order. So in this case you need to add this line "400000 50" as the first line of the model. Let me know if that helped.

Thanks a lot!
