### ISSUE TITLE
How to load pretrained model for DBPedia vectors

### ISSUE THREAD

**Issue by zhq2009** [3Top/word2vec-api#9]
I have download the DBPedia vectors (8.6GB) and extracted to get three files one is en.model another two are en.model.syn0.ny and en.model.syn1.npy, I try use the word2vec-api to load these file via:python word2vec-api --model path/to/the/model [--host host --port 1234], and try uses some sample calls:curl http://127.0.0.1:5000/word2vec/n_similarity?ws1=Sushi&ws1=Shop&ws2=Japanese&ws2=Restaurant
curl http://127.0.0.1:5000/word2vec/similarity?w1=Sushi&w2=Japanese
curl http://127.0.0.1:5000/word2vec/most_similar?positive=indian&positive=food[&negative=][&topn=]
curl http://127.0.0.1:5000/word2vec/model?word=restaurant
curl http://127.0.0.1:5000/word2vec/model_word_set

But I cannot load these files, how to load these files by using word2vec-api?

Thank you very much

**Comment by lechatpito** [comment]
you will find more information about DBpedia vectors here: https://github.com/idio/wiki2vec

**Comment by zhq2009** [comment]
Thank you for your help. 
For Google news data set, I can use "$ python word2vec-api.py --model GoogleNews-vectors-negative300.bin --binary GoogleNews-vectors-negative300.bin"
and get the program runs:" \* Running on http://localhost:5000/ (Press CTRL+C to quit)""

But for DBPedia data set, when I type "$ python word2vec-api.py --model en.model" , I will get some error message, "Traceback (most recent call last):
  File "word2vec-api.py", line 121, in <module>
    model = w.load_word2vec_format(model_path, binary=binary)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.4-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 1053, in load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.4-py2.7-linux-x86_64.egg/gensim/utils.py", line 217, in any2unicode
    return unicode(text, encoding, errors=errors)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte"

and same for en.model.syn0.nyp, en.model.syn1.npy.npy files in DBPedia.

How can I load the en.model and/or en.model.syn0.nyp, en.model.syn1.npy.npy files?

What I need to type in order to get the program runs?

**Comment by nishankmahore** [comment]
@zhq2009
you are writing the wrong syntax
correct syntax
python word2vec-api.py --model /apps/nishank/data/GoogleNews-vectors-negative300.bin --binary BINARY --path /algorithm --host 0.0.0.0 --port 5000
